# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_aGZ7Ww3v-Os7r7jBn5rdFQhrPF0kViL
"""

import random

equipo = "A"
numJugador = 1
numEqui = 0
golequipoA = 0
golequipoB = 0

print("LISTA DE JUGADORES POR EQUIPO:")
print("------------------------------")

while numEqui < 2:
    print(f"EQUIPO {equipo}")
    print("|     NOMBRE     |     POSICION     |   EDAD   |   GOLES   |")

    while numJugador <= 5:
        edad = random.randint(19, 40)
        goles = random.randint(0, 9)
        posicion = random.randint(1, 2)
        print(f"|   Jugador {equipo}{numJugador}   |    Posicion {posicion}    |    {edad}    |     {goles}     |")
        numJugador += 1

        if equipo == "A":
            golequipoA += goles
        else:
            golequipoB += goles

    numJugador = 1
    numEqui += 1
    equipo = "B"

numEqui = 0
golequipoA = 10
golequipoB = 10

print("ESTADISTICAS DEL PARTIDO:")
print("-------------------------")
print(f"Goles Equipo A: {golequipoA}")
print(f"Goles Equipo B: {golequipoB}")

if golequipoB < golequipoA:
    print("Equipo ganador: Equipo A")
elif golequipoB > golequipoA:
    print("Equipo ganador: Equipo B")
else:
    print("Ha terminado como un empate, se recurrirá a una ronda de penales")
    print("Penales:")
    equipo = "A"

    while numEqui < 2:
        print(f"Equipo {equipo}")
        while numJugador <= 5:
            goles = random.randint(0, 1)
            print(f"|   Jugador {equipo}{numJugador}  |     {goles}     |")
            numJugador += 1

            if equipo == "A":
                golequipoA += goles
            else:
                golequipoB += goles

        numJugador = 1
        numEqui += 1
        equipo = "B"

print("ESTADISTICAS DEL PARTIDO:")
print("-------------------------")
print(f"Goles Equipo A: {golequipoA}")
print(f"Goles Equipo B: {golequipoB}")

if golequipoB < golequipoA:
    print("Equipo ganador: Equipo A")
elif golequipoB > golequipoA:
    print("Equipo ganador: Equipo B")
else:
    print("Se ha entrado a ronda de muerte súbita")
    goles = 0
    equipo = "A"

    while goles == 0:
        num = 0
        goles = random.randint(0, 1)

        if goles <= 0:
            print(f"Jugador {equipo}{numJugador} falló")
            if equipo == "A":
                equipo = "B"
                if numJugador > 5:
                    numJugador = 0
                numJugador = numJugador - num
            else:
                equipo = "A"
                if numJugador == 5:
                    numJugador = 0
                numJugador += 1
        else:
            print(f"Jugador {equipo}{numJugador} anotó")
            print("El ganador es el equipo A")